require_relative 'config/environment'

desc "Loads a console"
task :console do
    Pry.start
end

desc "Says hi to the class"
task :say_hi do
    puts "Hello everyone"
end

desc "set up database"
task :db_setup do
    book_sql = <<-SQL
        CREATE TABLE IF NOT EXISTS books(
            id integer PRIMARY KEY,
            title varchar(255),
            author_id integer
        );
    SQL
    author_sql = <<-SQL 
        CREATE TABLE IF NOT EXISTS authors(
            id integer PRIMARY KEY,
            name varchar(255));
        SQL
    DB.execute(book_sql)
    DB.execute(author_sql)

end
